### ISSUE TITLE
Update integration tests to reflect CLI changes of type: name

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi-policy-aws#70]
https://github.com/pulumi/pulumi/pull/5773

**Comment by lukehoban** [comment]
P1 as this will break in two repos until addressed.

**Comment by jaxxstorm** [comment]
The tests still pass with with this change as we don't have any integrations tests (that I can find) that check the CLI output:

See https://github.com/pulumi/pulumi-policy-aws/pull/71 as an example
