### ISSUE TITLE
Publish 0.3.0 to npm for pulumi 3 support

### ISSUE THREAD

**Issue by mdop-wh** [pulumi/pulumi-policy-aws#76]
## Expected behavior

No error message when running `pulumi up` with awsguard policy pack

## Current behavior

This message occurs when running `pulumi up`

Found incompatible versions of @pulumi/pulumi. Differing major versions are not supported.
      Version 2.25.2 referenced at node_modules/@pulumi/awsguard/node_modules/@pulumi/pulumi/package.json
      Version 3.2.1 referenced at node_modules/@pulumi/pulumi/package.json

**Comment by stack72** [comment]
Hi @mdop-wh 

I am so sorry about this - TL;DR, I pushed the tag here but it looks like our build didn't pick it up!

I just retriggered it 

https://travis-ci.com/github/pulumi/pulumi-policy-aws/jobs/503531649

This should sort it out when the build completes

Paul

**Comment by mdop-wh** [comment]
👍  no worries thanks for the quick response @stack72.  Everything looks good now!

**Comment by stack72** [comment]
ok, 0.3.0 should now be on NPM!

Sorry again
