### ISSUE TITLE
acm-certificate-expiration policy doesn't correctly detect aws:region set in stack config.

### ISSUE THREAD

**Issue by arwilczek90** [pulumi/pulumi-policy-aws#77]
When running the policy pack the acm-certificate-expiration policy throws an error at Request.VALIDATE_REGION saying missing region in config when it exists in the pulumi config.

## Expected behavior
A certificate that passes policy with the correct values for accessing an aws account in the config file should pass correctly
## Current behavior
```
error: Error validating stack with policy acm-certificate-expiration:
    ConfigError: Missing region in config
        at Request.VALIDATE_REGION 
```
## Steps to reproduce

1. Install AWS Crossguard policy in stack
2. add acm certificate in component module
3. import component module in project.
3. add configuration in project for stack including aws:region
4. run pulumi up

## Context (Environment)

We have had to disable the acm-certificate-expiration policy which is non ideal.

**Comment by tusharshahrs** [comment]
This has been fixed by the following release for [pulumi-policy-aws](https://github.com/pulumi/pulumi-policy-aws/blob/master/CHANGELOG.md#024-2021-07-05).  **0.2.4**
